# Python - Numpy

In [ ]:
# pip install numpy
# conda activate --> pip install numpy
import numpy as np

In [ ]:
lst = [1,2,3,4,'asihfkdjhfkjsd']

In [ ]:
lst

In [ ]:
a = '1'
b = 1

print(a+'1')
print(b+1)

In [ ]:
np.array(lst)

In [ ]:
np.array([1,2,3])

In [ ]:
np.array((1,2,3))

In [ ]:
np.array({1,2,3})

In [ ]:
a = np.array({"a":1, "b":1})

In [ ]:
a.shape

In [ ]:
np.array([1,2,3,True, False])

In [ ]:
np.array([True, False, True])

In [ ]:
np.array([1,2,3,True, False,'abc'])

In [ ]:
if -1:  ## Anything non-zero is True
    print("Hello")
    
if 0: ## 0 means False
    print("World!!")

In [ ]:
np.zeros((3,4))   ## np.zeros(row_number, col_number)

In [ ]:
np.zeros([3,4])

In [ ]:
np.random.random([3,4])  ## np.random.random((row_numbers, col_numbers)/[row_numbers, col_numbers])

In [ ]:
np.full((3,4),5.5) ## np.full((row_numbers, col_numbers), number_to_fill)

In [ ]:
np.arange(1,10,2) ## np.arange(start_num, end_num, difference)

In [ ]:
np.arange(12) ## np.arange(number_of_elements) ==> Default starts from 0

In [ ]:
np.linspace(5,10,7) ## np.linspace(start_num, end_num, num_of_points)

In [ ]:
np.linspace(5,10,5)

In [ ]:
arr = np.array([[1,2,3,4],[1,2,8,7],[2,3,4,6]])

arr

In [ ]:
arr1 = np.array([[[2,17,19], [45, 78,81], [12, 15,17]], [[88, 92,90], [60, 76,91], [12, 15,17]],[[76,33,50],[20,18,25], [12, 15,17]]])

arr1

In [ ]:
arr1.shape

In [ ]:
arr.shape

In [ ]:
arr.ndim

In [ ]:
arr1.ndim

In [ ]:
arr_shape = arr.shape
arr1_shape = arr1.shape


arr_rows = arr_shape[0]
arr_columns = arr_shape[1]

arr1_rows = arr1_shape[0]
arr1_rows_rows = arr1_shape[1]
arr1_rows_columns = arr1_shape[2]

In [ ]:
print(arr_rows, arr_columns, arr1_rows, arr1_rows_rows, arr1_rows_columns)

In [ ]:
arr.dtype

In [ ]:
a = np.zeros((3,4))

a.dtype

In [ ]:
a = np.full((3,4), 'abjshdfbkhsjdf')
a.dtype

In [ ]:
arr1.size

In [ ]:
arr.size

In [ ]:
arr = np.arange(12)

arr

In [ ]:
arr.shape

In [ ]:
arr = arr.reshape((4,3))

In [ ]:
arr.shape

In [ ]:
arr

In [ ]:
a = [[1,  2,  3], [2,  5,  7]]
b = [[1,  2,  3], [3,  5 , 7]]
c = [[1,  3,  5], [1,  2,  3]]

np.equal(a, b)

In [ ]:
np.equal(a, c)

In [ ]:
np.equal(b, c)

In [ ]:
np.array_equal(a,b)

In [ ]:
np.array_equal( [[1,  2,  3], [2,  5,  7]], [[1,  2,  3], [2,  5 , 7]])

In [3]:
import numpy as np

a = np.array([5,10])
b = np.array([2,3])

print(a)
print(b)

print(np.sum(a))
print(np.sum(b))

print(np.sum([a,b]))

# [
#   5 10
#   2 3
# ]


## Axis = 1 ==> Row wise operation
## Axis = 0 ==> Column wise operation

print(np.sum([a,b], axis=1))
print(np.sum([a,b], axis=0))

[ 5 10]
[2 3]
15
5
20
[15  5]
[ 7 13]


In [4]:
c = np.array([[1,2,4],[3,4,6]])
d = np.array([[2,4,8],[5,7,9]])
print(c)
print("------------------------------------")
print(d)

[[1 2 4]
 [3 4 6]]
------------------------------------
[[2 4 8]
 [5 7 9]]


In [5]:
print(np.sum(c))
print(np.sum(d))

print(np.sum([c,d]))

#[ 
#  [1 2 4
#  3 4 6] 
#]


print(np.sum([c,d],axis=1))
print(np.sum([c,d],axis=0))

20
35
55
[[ 4  6 10]
 [ 7 11 17]]
[[ 3  6 12]
 [ 8 11 15]]


In [34]:
print(np.subtract(c,d))

print(np.multiply(c,d))
print(np.divide(c,d))

print(np.sqrt(c))
print(np.exp(c))
print(np.log(a))
print(np.sin(a))
print(np.cos(a))

[[-1 -2 -4]
 [-2 -3 -3]]
[[ 2  8 32]
 [15 28 54]]
[[0.5        0.5        0.5       ]
 [0.6        0.57142857 0.66666667]]
[[1.         1.41421356 2.        ]
 [1.73205081 2.         2.44948974]]
[[  2.71828183   7.3890561   54.59815003]
 [ 20.08553692  54.59815003 403.42879349]]
[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]


In [10]:
a = np.array([[1,2,3],[4,5,6]])
print("Sum of the list " , np.sum(a))
print("Minimum elem of the list " , np.min(a))
print("Maximum elem of the list ", np.max(a))


print("Mean of the data points " , np.mean(a))
print("Median of the data points " , np.median(a))

print("Standarad Deviation of the points ", np.std(a))
print("Correlation Coefficient of the list " , np.corrcoef(a))

Sum of the list  21
Minimum elem of the list  1
Maximum elem of the list  6
Mean of the data points  3.5
Standarad Deviation of the points  1.707825127659933
Median of the data points  3.5
Correlation Coefficient of the list  [[1. 1.]
 [1. 1.]]


In [11]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
b = np.array([[3,4,5],[6,7,8]])
print(b)
#axis = 0 => row wise
#axis = 1 => column wise
print("Horizontal Concat Resut for axis {} is {}".format(0,np.concatenate([a,b],axis=0)))
print("Vertical Concat Resut for axis {} is {}".format(1,np.concatenate([a,b],axis=1)))

[[1 2 3]
 [4 5 6]]
[[3 4 5]
 [6 7 8]]
Horizontal Concat Resut for axis 0 is [[1 2 3]
 [4 5 6]
 [3 4 5]
 [6 7 8]]
Vertical Concat Resut for axis 1 is [[1 2 3 3 4 5]
 [4 5 6 6 7 8]]


In [12]:
np.stack((a,b),axis=0)

array([[[1, 2, 3],
        [4, 5, 6]],

       [[3, 4, 5],
        [6, 7, 8]]])

In [13]:
np.stack((a,b),axis=1)

array([[[1, 2, 3],
        [3, 4, 5]],

       [[4, 5, 6],
        [6, 7, 8]]])

In [14]:
np.hstack([a,b])

array([[1, 2, 3, 3, 4, 5],
       [4, 5, 6, 6, 7, 8]])

In [15]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
np.column_stack((a,b))

array([[1, 2, 3, 3, 4, 5],
       [4, 5, 6, 6, 7, 8]])

In [18]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[2,3,4],[5,6,7]])

print("A Matrix ---")
print(a)
print("B Matrix ---")
print(b)
print("Horizontal Stack---")
print(np.hstack((a,b)))
print("Vertical Concat---")
print(np.concatenate((a,b),axis=1))
print("Column Stack---")
print(np.column_stack((a,b)))

print("Horizontal Concat---")
print(np.concatenate((a,b),axis=0))
print("Vertical Stack---")
print(np.vstack((a,b)))

A Matrix ---
[[1 2 3]
 [4 5 6]]
B Matrix ---
[[2 3 4]
 [5 6 7]]
Horizontal Stack---
[[1 2 3 2 3 4]
 [4 5 6 5 6 7]]
Vertical Concat---
[[1 2 3 2 3 4]
 [4 5 6 5 6 7]]
Column Stack---
[[1 2 3 2 3 4]
 [4 5 6 5 6 7]]
Horizontal Concat---
[[1 2 3]
 [4 5 6]
 [2 3 4]
 [5 6 7]]
Vertical Stack---
[[1 2 3]
 [4 5 6]
 [2 3 4]
 [5 6 7]]


## Number of split should be a factor of total number of elements & it should be lte number of rows or columns based on the direction of operation (either row wise or column wise)

In [26]:
x = np.arange(16).reshape(4,4)
print(x)
print(np.hsplit(x,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[ 0],
       [ 4],
       [ 8],
       [12]]), array([[ 1],
       [ 5],
       [ 9],
       [13]]), array([[ 2],
       [ 6],
       [10],
       [14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]


In [27]:
print(np.vsplit(x,2))

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


In [31]:
print(np.split(x,2,axis = 1))
print(np.split(x,2,axis=0))

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


In [33]:
x = np.arange(25).reshape(5,5)
print(x)
print(np.hsplit(x,np.array([2,3]))) #x[:,:2], x[:, 2:3], x[:, 3:]
print(np.vsplit(x,np.array([2,3]))) #x[:2,:], x[2:3,:], x[3:,:]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[array([[ 0,  1],
       [ 5,  6],
       [10, 11],
       [15, 16],
       [20, 21]]), array([[ 2],
       [ 7],
       [12],
       [17],
       [22]]), array([[ 3,  4],
       [ 8,  9],
       [13, 14],
       [18, 19],
       [23, 24]])]
[array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14]]), array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])]


In [39]:
import sys

#define a list
l= []

for i in range(10000):
    l.append(i)

print("Size of a type {} of length {} is : {} ".format(type(l),len(l),sys.getsizeof(l[0])*len(l)))

#define a numpy array
a = np.arange(10000)
print("Size of an type {} of length {} is : {} ".format(type(a),a.size, a.size*a.itemsize))

print(f"Numpy array is {(sys.getsizeof(l[0])*len(l)) / (a.size*a.itemsize)} times cheaper than python lists")

Size of a type <class 'list'> of length 10000 is : 240000 
Size of an type <class 'numpy.ndarray'> of length 10000 is : 80000 
Numpy array is 3.0 times cheaper than python lists


In [42]:
#Numpy vs List: Speed
import time

def using_List():
    t1 = time.time()#Starting/Initial Time
    X = range(100000)
    Y = range(100000)
    z = [X[i]+Y[i] for i in range(len(X))]
    return time.time()-t1

def using_Numpy():
    t1 = time.time()#Starting/Initial Time
    a = np.arange(100000)
    b = np.arange(100000)
    z = a + b #more convient than a list
    return time.time()-t1

list_time = using_List()
numpy_time = using_Numpy()

print("Time taken for list is {} and Time taken for numpy array is {}".format(list_time,numpy_time))
print("In this example Numpy is "+str(list_time/numpy_time)+" times faster than a list")

Time taken for list is 0.022678136825561523 and Time taken for numpy array is 0.00199127197265625
In this example Numpy is 11.388769157088122 times faster than a list
